<?php

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist): ?>
    <div class="block widget block-new-products <?php echo $mode; ?>">
        <?php if ($this->getData('params/title')): ?>
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php echo $this->getData('params/title') ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items <?php echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item):
                        ?><?php echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name"> <a
                                            title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                            href="<?php echo $block->getProductUrl($_item) ?>"
                                            class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a> </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>
                            </div>
                        </div>
                        <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?><?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
